#+TITLE: Minutes of mtg with Advisor
#+AUTHOR: Sai Gollapudi
WHEN: 13 Aug, 2015
WHERE: IIIT-Hyd, Prof. Office
WHO: Sai Gollapudi (SG) with Prof. Venkatesh Choppella (VC)

In the mtg we discussed the following:
+ Author may write something from his / her point of view. But, it
  does not mean that the viewers would all want to see it from the
  same point of view.
+ the viewers point of view may be based on their preferences. Their
  preferences are their semantic style sheets (SSS).
+ an author may write "35 degrees Fahrenheigh"... but this will remain
  as text. It is not called out as a type or a special unit to be
  transformed.
+ If original document D has only text, then how do we renarrate that
  D in multiple ways depending on the stylesheets of various users?
+ for renarrating D we need to have a annoted D called D'. In this
  case, D' should have maybe a XML or a JSON marking around the 35F to
  call it out for applying either a transformation or a web service on
  it.
+ the semantic style sheet (SSS) can be on the local database of the user
  (on the laptop)
+ When viewing a source page D, the input from the SSS should be able
  to influence what is seen on D. to modify the D in a way that suits
  SSS, one must be able to pluck out data-types (like temp, units,
  currency) and tag them. 
+ There is no need to be wedded to any one method for tagging. Sweets
  are just one method.
+ A web resource D can be modified into D' by identifying the data
  types and tagging. This can be done in one of many ways: Machine
  Learning, Search & Extraction methods of Data Mining, Neural Network
  methods, Type Inference etc. It could also be human / manual with
  annotation by crowdsourcing.
+ This work can be informed by the following CS topics: Languages
  (Data Types), Architecture (Web), Program Transformation
+ Should be able to work on thesis chapter now itself. First quantize
  the assessibility issue. Have chapters on architecture, design,
  impelementation, validation
+ VC suggested that SG come up with a more "tighter" not "diffused" research direction and
  plan on this problem.
+ VC volunteered 50% of Annon's time for this project.

